### ISSUE TITLE
Any schedule on releasing your code?

### ISSUE THREAD

**Issue by xushangnjlh** [rulllars/SequentialVisualLocalization#1]
RT

**Comment by Zumbalamambo** [comment]
+1

**Comment by rulllars** [comment]
Great to see that you are interested in the code. We are currently working actively to clean-up the codebase to make it more presentable for others and hope to be able to publish the code within the coming week(s).

Stay tuned!

/Lars

**Comment by WellYoungIOE** [comment]
> Great to see that you are interested in the code. We are currently working actively to clean-up the codebase to make it more presentable for others and hope to be able to publish the code within the coming week(s).
> 
> Stay tuned!
> 
> /Lars

Half a year has passed.  Will you release your code?

**Comment by HawkYJH** [comment]
Any schedule on releasing your code?+1

**Comment by rulllars** [comment]
Code is available now.
