### ISSUE TITLE
Inquiry regarding the availability of example data for the Sequential CMU Seasons Dataset.

### ISSUE THREAD

**Issue by kimjh069** [rulllars/SequentialVisualLocalization#4]
Thank you for sharing such valuable work. 
I am currently in the process of revising my paper and I would greatly appreciate the opportunity to test the example data and cite your paper "Using Image Sequences for Long-Term Visual Localization."
I noticed that the Sequential CMU Seasons Dataset for LocSLAM is not currently available. 
Would it be possible for you to inform me of any planned release schedule for the example data or if there any chance that I could request an example sequential data to run your code?

**Comment by kimjh069** [comment]
Closing the issue.

**Comment by yuancaimaiyi** [comment]
@kimjh069  
hello, Do you solved this problem?

**Comment by kimjh069** [comment]
> @kimjh069 hello, Do you solved this problem?

No. My paper was published without including experiments using LocSLAM.
